### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by OnlineCop** [shaovoon/concurrent_permcomb#3]
Your https://www.codeproject.com/Articles/1247260/Cplusplus-Simple-Permutation-and-Combination-Paral page points here and includes a CPOL license. Could that license (or another one if more appropriate) be included in this repo?

> This article, along with any associated source code and files, is licensed under [The Code Project Open License (CPOL)](http://www.codeproject.com/info/cpol10.aspx)

**Comment by shaovoon** [comment]
License added
